# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Gina Soileau"

description: "Fast times at Metis Data Science Bootcamp"


email: gfsoileau@gmail.mail
#blog logo
logo: "/assets/images/gs.png"
# blog cover
cover: "/assets/images/hi.jpg"

name: 'Gina Soileau'
author: 'Gina Soileau'
author_image: "/assets/images/gina.jpg"

paginate:	5

url: "http://gfsoileau.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https:https://www.linkedin.com/in/gfsoileau
    desc:
    share_url:
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/gfsoileau
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/gfsoileau
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/gfsoileau
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
